board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')), 
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    path('create/', views.create, name='create'),

    path('<int:post_id>/create/comment/', views.comment_create, name='comment_create'),

    path('<int:post_id>/comment/<int:id>/delete/', views.delete, name='delete'),

    path('<int:id>/update/', views.update, name='update'),
]

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm

# Create your views here.

def index(request):
    posts = Post.objects.all()

    context = {
        'posts': posts
    }

    return render(request, 'index.html', context)


def detail(request,id):
    post = Post.objects.get(id=id)
    comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form': comment_form,
    }

    return render(request, 'detail.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('posts:index')

    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        comment.post_id = post_id

        comment.save()

        return redirect('posts:detail', id=post_id)


def delete(request, post_id, id):
    comment = Comment.objects.get(id=id)

    comment.delete()

    return redirect('posts:detail', id=post_id)

def update(request, id):
    post = Post.objects.get(id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            return redirect('posts:detail', id=id)

    else:
        form = PostForm(instance=post)

    context = {
        'form': form
    }

    return render(request, 'update.html', context)

posts/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{post.title}}</h1>
    <p>{{post.content}}</p>
    <p>{{post.created_at}}</p>

    <hr>

    <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit">
    </form>

    <a href="{% url 'posts:update' id=post.id %}">수정</a>

    <hr>
    {% for comment in post.comment_set.all %}
        <p>
            {{comment.content}}
            <a href="{% url 'posts:delete' post_id=post.id id=comment.id %}">삭제</a>
        </p>
    {% endfor %}
{% endblock %}

posts/templates/form.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>


{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index</h1>

    {% for post in posts %}
        <h2>{{post.title}}</h2>
        <a href="{% url 'posts:detail' id=post.id %}">detail</a>
        <hr>
    {% endfor %}
{% endblock %}

posts/templates/update.html
{% extends 'base.html' %}

{% block body %}

    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <a href="{% url 'posts:index' %}">Home</a>
    <a href="{% url 'posts:create' %}">Create</a>

    {% block body %}
    
    {% endblock %}
</body>
</html>